### ISSUE TITLE
crash at startup

### ISSUE THREAD

**Issue by monowii** [Taiko2k/TauonMusicBox#1017]
os: Ubuntu 22.04.3 LTS
flatpak: 7.6.6

For no apparent reason the window size preference changed

```
Window size: [0, 0]
Error accessing GTK settings
Detected running as Flatpak
Installed as Flatpak
User files location: /home/USER/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Found XDG-Downloads: /home/USER/Downloads
Found XDG-Music: /home/USER/Music
Install directory: /app/bin
Database loaded in 0.151 seconds.
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 352, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 4309, in <module>
    auto_scale()
  File "/app/bin/t_modules/t_main.py", line 4278, in auto_scale
    prefs.scale_want = window_size[0] / logical_size[0]
ZeroDivisionError: division by zero
```

also tried deleting window.p file but the same error happen as
```
No window state file
Window size: [0, 0]
```

**Comment by Taiko2k** [comment]
Probably an external issue related to video drivers. Try update your system, reboot, and run `flatpak update`

**Comment by monowii** [comment]
Wow yeah it's fixed, It only stopped working yesterday.
Probably the flatpak update I did from yesterday broke it temporarily.
