### ISSUE TITLE
Radio doesn't work

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#1033]
v7.6.7 flatpak

Radio doesn't work after update:

```
Open URL.....
URL opened.
audio/mpeg
/usr/bin/ffmpeg: symbol lookup error: /usr/lib/x86_64-linux-gnu/libavfilter.so.9: undefined symbol: swr_alloc_set_opts2, version LIBSWRESAMP
LE_4
Exception in thread Thread-29 (feed):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_stream.py", line 182, in feed
    decoder.stdin.write(chunk)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by Taiko2k** [comment]
Can reproduce. Ive issued a new flatpak update that should resolve this issue. (May take a few hours to publish from time of this posting)
