### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by chris246** [Taiko2k/TauonMusicBox#1034]
Tauon v7.6.7 crashes on startup:

```
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 359, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 4333, in <module>
    auto_scale()
  File "/app/bin/t_modules/t_main.py", line 4302, in auto_scale
    prefs.scale_want = window_size[0] / logical_size[0]
                       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

**Comment by Spicytin** [comment]
Have the same issue, it occurs after enabling "prefer x11 on wayland" then restarting the app

**Comment by yodatak** [comment]
Same too

**Comment by C0rn3j** [comment]
I've added https://github.com/Taiko2k/Tauon/pull/1311/commits/c3fdb483779ad974225f48d0a2172aeb1ef26e83 in my PR to crash properly earlier when it happens.

The problem is that `SDL_CreateWindow()` somehow fails, so the resulting res was doing `0/0`.

This seems exclusive to Flatpak, and the linked issue is not the problem, earlier path from __main__ is.

```python
t_window = SDL_CreateWindow(
	window_title,
	o_x, o_y,
	logical_size[0], logical_size[1],
	flags) 
```
It seems to be passing the same parameters as my working native version, no clue why it actually fails.

**Comment by Taiko2k** [comment]
Most common reason for failure is mismatched Flatpak/host Nvidia driver.

**Comment by C0rn3j** [comment]
Not the case on my system, I am running Plasma Wayland with 565.57.01 both in Flatpak and host

**Comment by C0rn3j** [comment]
So the current master throws this:

`[ ERROR ] [ __main__ ] SDL Error: b'x11 not available' (__main__.py:357)`

**Comment by Thermo-Dyn** [comment]
Tauon also does not automatically delete the `x11` file it creates after crashing with it

**Comment by C0rn3j** [comment]
@Taiko2k How about we just hide the button on Flatpak and call it a day?

I was unable to get Xwayland working in the Flatpak, and there's not a whole lot of reasons why people might want to force Xwayland in the first place.

**Comment by Copernicium282** [comment]
Is this resolved? it somewhat looks like to me but can't confirm, i can probably test on both  x11 and wayland on KDE
it does seem flatpak specific as i run tauon on x11 daily with no issues

**Comment by C0rn3j** [comment]
It is not.
