### ISSUE TITLE
Crash when trying to play FLAC track

### ISSUE THREAD

**Issue by Movisivi** [Taiko2k/TauonMusicBox#1051]
Tauon AUR 7.6.7

Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 359, in <module>
    exec(main)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 45995, in <module>
    queue_box.draw(0, gui.panelY + pl_box_h, gui.lspw, full - pl_box_h)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 38800, in draw
    elif playlist[i] != item[0]:
         ~~~~~~~~^^^
IndexError: list index out of range

**Comment by Taiko2k** [comment]
Ive now committed a fix which I think should fix this

**Comment by Movisivi** [comment]
All good now! Thanks :)
