### ISSUE TITLE
FileNotFoundError... Why is tauon looking for steampath?

### ISSUE THREAD

**Issue by shervinsahba** [Taiko2k/TauonMusicBox#1127]
```
└─❯ tauon 
Tauon Music Box v7.7.2
Copyright 2015-2023 Taiko2k captain.gxj@gmail.com

Window size: [1682, 1344]
2021
Running from installed location
User files location: /home/shervin/.local/share/TauonMusicBox
Found XDG-Downloads: /home/shervin/Downloads
Found XDG-Music: /home/shervin/
Install directory: /opt/tauon-music-box
Database loaded in 0.03 seconds.
Pychromecast not found
Error loading xcursor
Start controller server
Start PHAzOR backend...
DEBUG: WASAPI backend is disabled.
DEBUG: DirectSound backend is disabled.
DEBUG: WinMM backend is disabled.
DEBUG: Core Audio backend is disabled.
DEBUG: sndio backend is disabled.
DEBUG: audio(4) backend is disabled.
DEBUG: OSS backend is disabled.
DEBUG: Attempting to initialize PulseAudio backend...
DEBUG: Loading library: libpulse.so
DEBUG: Loading symbol: pa_mainloop_new
DEBUG: Loading symbol: pa_mainloop_free
DEBUG: Loading symbol: pa_mainloop_quit
DEBUG: Loading symbol: pa_mainloop_get_api
DEBUG: Loading symbol: pa_mainloop_iterate
DEBUG: Loading symbol: pa_mainloop_wakeup
DEBUG: Loading symbol: pa_threaded_mainloop_new
DEBUG: Loading symbol: pa_threaded_mainloop_free
DEBUG: Loading symbol: pa_threaded_mainloop_start
DEBUG: Loading symbol: pa_threaded_mainloop_stop
DEBUG: Loading symbol: pa_threaded_mainloop_lock
DEBUG: Loading symbol: pa_threaded_mainloop_unlock
DEBUG: Loading symbol: pa_threaded_mainloop_wait
DEBUG: Loading symbol: pa_threaded_mainloop_signal
DEBUG: Loading symbol: pa_threaded_mainloop_accept
DEBUG: Loading symbol: pa_threaded_mainloop_get_retval
DEBUG: Loading symbol: pa_threaded_mainloop_get_api
DEBUG: Loading symbol: pa_threaded_mainloop_in_thread
DEBUG: Loading symbol: pa_threaded_mainloop_set_name
DEBUG: Loading symbol: pa_context_new
DEBUG: Loading symbol: pa_context_unref
DEBUG: Loading symbol: pa_context_connect
DEBUG: Loading symbol: pa_context_disconnect
DEBUG: Loading symbol: pa_context_set_state_callback
DEBUG: Loading symbol: pa_context_get_state
DEBUG: Loading symbol: pa_context_get_sink_info_list
DEBUG: Loading symbol: pa_context_get_source_info_list
DEBUG: Loading symbol: pa_context_get_sink_info_by_name
DEBUG: Loading symbol: pa_context_get_source_info_by_name
DEBUG: Loading symbol: pa_operation_unref
DEBUG: Loading symbol: pa_operation_get_state
DEBUG: Loading symbol: pa_channel_map_init_extend
DEBUG: Loading symbol: pa_channel_map_valid
DEBUG: Loading symbol: pa_channel_map_compatible
DEBUG: Loading symbol: pa_stream_new
DEBUG: Loading symbol: pa_stream_unref
DEBUG: Loading symbol: pa_stream_connect_playback
DEBUG: Loading symbol: pa_stream_connect_record
DEBUG: Loading symbol: pa_stream_disconnect
DEBUG: Loading symbol: pa_stream_get_state
DEBUG: Loading symbol: pa_stream_get_sample_spec
DEBUG: Loading symbol: pa_stream_get_channel_map
DEBUG: Loading symbol: pa_stream_get_buffer_attr
DEBUG: Loading symbol: pa_stream_set_buffer_attr
DEBUG: Loading symbol: pa_stream_get_device_name
DEBUG: Loading symbol: pa_stream_set_write_callback
DEBUG: Loading symbol: pa_stream_set_read_callback
DEBUG: Loading symbol: pa_stream_set_suspended_callback
DEBUG: Loading symbol: pa_stream_set_moved_callback
DEBUG: Loading symbol: pa_stream_is_suspended
DEBUG: Loading symbol: pa_stream_flush
DEBUG: Loading symbol: pa_stream_drain
DEBUG: Loading symbol: pa_stream_is_corked
DEBUG: Loading symbol: pa_stream_cork
DEBUG: Loading symbol: pa_stream_trigger
DEBUG: Loading symbol: pa_stream_begin_write
DEBUG: Loading symbol: pa_stream_write
DEBUG: Loading symbol: pa_stream_peek
DEBUG: Loading symbol: pa_stream_drop
DEBUG: Loading symbol: pa_stream_writable_size
DEBUG: Loading symbol: pa_stream_readable_size
Using SDL version: 2.30.2
DEBUG: System Architecture:
DEBUG:   Endian: LE
DEBUG:   SSE2:   YES
DEBUG:   AVX2:   NO
DEBUG:   NEON:   NO
Adjust bg vertical
Applying theme: Neon Love

(tauon.py:412366): Gdk-CRITICAL **: 12:00:58.812: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Adjust bg vertical
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 352, in <module>
    from t_modules import t_main
  File "/opt/tauon-music-box/t_modules/t_main.py", line 43685, in <module>
    dl_mon.scan()
  File "/opt/tauon-music-box/t_modules/t_main.py", line 41380, in scan
    stamp = os.path.getmtime(path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 55, in getmtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/shervin/.steampath'
```

Not sure what is happening here. Why is tauon crashing, and why would it be looking for .steampath? Also, .steampath exists on my system as a symbolic link. I'm on 6.8.4-arch1-1 with Tauon v7.7.2.

**Comment by Taiko2k** [comment]
Its the download monitor feature doing that. Normally once enabled it only looks in the top level of the Downloads and Music folders. Not sure why it would look there. Did you ever add anything to Tauons config file?

Ive committed a fix so at least it wont crash.

**Comment by shervinsahba** [comment]
Thanks for checking it out, Taiko.

I see the error now. It's totally on my end. The config is fine, by the way.

It looks like my XDG music directory, `/home/$USER/Music`, was somehow erroneously changed to `/home/$USER`. From the debug log above, there's this line
```
Found XDG-Music: /home/shervin/
```

So `tauon` was doing its job at scanning my entire home directory. When it hit `~/.steampath` it broke, because it looks like this is a defunct symbolic link that leads to nothing.
```
└─❯ ll .steampath 
lrwxrwxrwx shervin shervin 32 B Tue Apr  9 12:12:23 2024  .steampath@ ⇒ /home/shervin/.steam/sdk32/steam

┌[  ~  ]-                                                                                                    
└─❯ ll /home/shervin/.steam/sdk32/steam
lsd: /home/shervin/.steam/sdk32/steam: No such file or directory (os error 2).
```

Anyway, the fix on my end is simple!

```
xdg-user-dirs-update --set MUSIC /home/$USER/Music
```
