### ISSUE TITLE
Caused a crash when testing auto-theme + Carbon theme

### ISSUE THREAD

**Issue by curbia** [Taiko2k/TauonMusicBox#1134]
Some albums were not generating colours so I closed Tauon, and now it won't reopen. Installed as flatpak, and when I launch from terminal:

```
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 352, in <module>
    from t_modules import t_main
  File "/app/bin/t_modules/t_main.py", line 43046, in <module>
    load_theme(c, theme[0])
  File "/app/bin/t_modules/t_themeload.py", line 143, in load_theme
    colours.playlist_panel_background = get_colour_from_line(p)
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/t_modules/t_themeload.py", line 51, in get_colour_from_line
    r = int(ll[0] + ll[1], 16)
        ^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: 'tr'
```

I have tried removing `state.p`, `state.p.backup`, and `tauon.conf` from my install folder but it still crashes. :(

How to turn off auto-theming without launching? The error seems to be caused by one of the auto-colour functions.

**Comment by curbia** [comment]
I managed to get it working again but I had to delete the entire `~/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox` folder and re-implement my settings from scratch. Leaving this up because this error might be important for fixing an algorithm.

**Comment by Taiko2k** [comment]
Yeah looks like a bug that should be fixed. But it looks like to me the trigger is a malformatted theme file rather than an internal setting. Were you editing any theme files before this crash perchance?

**Comment by curbia** [comment]
None of the default ones, and I never activated any custom one because I hadn't done anything more than make a list of all the possible valued by copy-pasting together lines from a few different themes. I had Carbon active when this happened.

**Comment by C0rn3j** [comment]
@Taiko2k it is malformed themes, here's examples that'll crash it due to it being classified as a hex mode value

```ini
track1        mini text 2
truest        mini text 2
0xtrackff     mini text 2
```

EDIT: I've added tests for the function, see `pytest tauon/tests/disabled_test_get_colour_from_line.py`.

At the moment Tauon will also create nonsensical colours going past 255 from malformed lines too.

**Comment by C0rn3j** [comment]
Fixed by #2062, thanks for the report.
