### ISSUE TITLE
Windows startup problem [ImportError: DLL load failed...]

### ISSUE THREAD

**Issue by Looooopy** [Taiko2k/TauonMusicBox#1142]
When I downloaded the latest version (Maybe the same with other version have not tested) I get this dialog pop up in my face on startup :)

I am used to use it in on MacOS and Linux but now was trying it on windows and it failed!

```
Traceback (most recent call last):
  File "tauon.py", line 352, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "t_modules/t_main.py", line 671, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "t_modules/t_topchart.py", line 24, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "cairo/__init__.py", line 1, in <module>
ImportError: DLL load failed while importing _cairo: The specified procedure could not be found.
```

Do someone have a clue?

**Comment by Taiko2k** [comment]
This happens if you have an older version previously installed. Uninstalling, deteting tauons program folder and reinstalling should fix it

**Comment by Looooopy** [comment]
I did like you said, went to remove it through "Add and remove Programs". Then reinstalled it again and it worked!
Thanks!
