### ISSUE TITLE
Wont work on Xubuntu 19.04

### ISSUE THREAD

**Issue by NusryNizam** [Taiko2k/TauonMusicBox#140]
```
Tauon Music Box
v4.5.0
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Running in portable mode
Install directory: /home/nusry/Downloads/Tauon.Music.Box.v4.5.0.Linux.Bass.64bit/tauon-music-box
Could not set process title.
PyLast moduel not found, last fm will be disabled.
Traceback (most recent call last):
  File "/home/nusry/Downloads/Tauon.Music.Box.v4.5.0.Linux.Bass.64bit/tauon-music-box/PyLyrics/classes.py", line 3, in <module>
    from .functions import *
  File "/home/nusry/Downloads/Tauon.Music.Box.v4.5.0.Linux.Bass.64bit/tauon-music-box/PyLyrics/functions.py", line 2, in <module>
    from bs4 import BeautifulSoup, Comment, NavigableString
ModuleNotFoundError: No module named 'bs4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nusry/Downloads/Tauon.Music.Box.v4.5.0.Linux.Bass.64bit/tauon-music-box/PyLyrics/__init__.py", line 6, in <module>
    from .classes import *
  File "/home/nusry/Downloads/Tauon.Music.Box.v4.5.0.Linux.Bass.64bit/tauon-music-box/PyLyrics/classes.py", line 5, in <module>
    from functions import *
ModuleNotFoundError: No module named 'functions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tauon.py", line 312, in <module>
    from PyLyrics import *
  File "/home/nusry/Downloads/Tauon.Music.Box.v4.5.0.Linux.Bass.64bit/tauon-music-box/PyLyrics/__init__.py", line 10, in <module>
    from classes import *
ModuleNotFoundError: No module named 'classes'
```

**Comment by Taiko2k** [comment]
Actually that zip package isn't intended to be used just by itself, its used by the AUR script. There are multiple dependencies that would need to also be installed to get running.

If you just want to try the app, I'd recommend the Flatpak package. I don't have exact instructions for setup from source for Ubuntu.
