### ISSUE TITLE
Quits when playing certain songs

### ISSUE THREAD

**Issue by floeschen** [Taiko2k/TauonMusicBox#203]
Recently, whenever I play certain songs the player quits/crashes immediately. No error message or anything else. The behaviour does not seem to be consistent across albums, songs with special characters in the file name or title or artist.

Below I give you the output of the syslog. I replaced my host name and my home directory. I run Ubuntu 19.10 and have installed Tauon Music Box via Flatpak.

As far as I understand it, there is some issue around cover images of the tracks. I have re-added the cover images to the songs causing the crashes but there is no change.

```
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Tauon Music Box v5.0.3
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Copyright 2015-2019 Taiko2k captain.gxj@gmail.com
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Detected running as Flatpak
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: -- Symlink to user fonconfig exists
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Running from installed location
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: User files location: /home/user/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Found XDG-Downloads: /home/user/Downloads
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Found XDG-Music: /home/user/Musik
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Install directory: /app/bin
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Could not set process title.
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Database loaded in 0.07 seconds.
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Locale detected: de_CH
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: No translation file available
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Could not connect to gnome media keys
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Thumbnail error
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Using SDL version: 2.0.10
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Config reload theme...
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Applying external theme: Cucumber Splash
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Theme number: 3
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Enabling garbage collecting
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Traceback (most recent call last):
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:   File "/app/bin/tauon.py", line 31865, in <module>
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:     playlist_render.full_render()
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:   File "/app/bin/tauon.py", line 23356, in full_render
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:     pctl.jump(track_id, track_position)
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:   File "/app/bin/tauon.py", line 3502, in jump
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:     self.play_target(jump=True)
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:   File "/app/bin/tauon.py", line 3470, in play_target
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:     self.notify_update()
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:   File "/app/bin/tauon.py", line 3111, in notify_update
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:     self.mpris.update()
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:   File "/app/bin/t_modules/t_dbus.py", line 160, in update
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:     self.PropertiesChanged('org.mpris.MediaPlayer2.Player', changed, [])
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:   File "/app/lib/python3.7/site-packages/dbus/decorators.py", line 325, in emit_signal
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]:     message.append(signature=signature, *args)
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: ValueError: embedded null byte
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Set output device as: PulseAudio Sound Server
Nov 10 13:09:40 host com.github.taiko2k.tauonmb.desktop[2253]: Open file: /home/user/Musik/Sigur Rós/Takk.._/01 Takk.._.m4a
Nov 10 13:09:40 host systemd[1917]: flatpak-com.github.taiko2k.tauonmb-22316.scope: Succeeded.
```

**Comment by Taiko2k** [comment]
I see that track it crashed on is an **m4a** file, could it be that the ones it crashes on are all/only m4a?

**Comment by floeschen** [comment]
Yes, it appears to be the case, that only m4a files are causing this behaviour. Most songs work fine, and I could not test all of them.

I have these files for quite a long time, though probably changed some metadata in the months before installing Tauon Music Box. In the last few days I let Music Brainz Picard redo all the metadata for these albums to no change.

Just after v 5.0.0 I realized this problem. When I installed Tauon Music Box in August (?) the problem was not there.

**Comment by Taiko2k** [comment]
If you are willing to send me one of the files causing the issue, that could be helpful.

Otherwise, when in Picard, you could try having the setting "Clear existing tags" enabled when writing tags and see if that solves the issue.

![Screenshot from 2019-11-11 11-49-19](https://user-images.githubusercontent.com/17271572/68552259-d6d41a80-0479-11ea-806a-67f6c22db69b.png)

**Comment by Taiko2k** [comment]
I've pushed an update with a change that may fix this. Try update then reload the metadata. (Right click playlist tab > Misc... > Rescan Tags)
