### ISSUE TITLE
Crash Windows versión with streaming ..

### ISSUE THREAD

**Issue by emipta** [Taiko2k/TauonMusicBox#238]
Hi Taiko! 

Thanks for build windows versión.

Problem, always when playing 3 o 4 minutes crashing, maybe you're new version 5.2.1 fixed this problem ? ...  

![capture](https://user-images.githubusercontent.com/37155732/73984894-18ba1300-493a-11ea-8f14-7e6a853ff368.png)

**Comment by Taiko2k** [comment]
If you look in the user data folder, there should be a file named `crash.log`. Can you open that and show me the relevant error? (Like, the last 10 lines)

**Comment by emipta** [comment]
Sorry ... for waiting... 

2020-02-06 23:25:48,193 ERROR root Exception on player thread
Traceback (most recent call last):
  File "tauon.py", line 6388, in bass_player_thread
  File "t_modules\t_bass.py", line 1375, in player
  File "tauon.py", line 4121, in test_progress
  File "tauon.py", line 4593, in advance
  File "tauon.py", line 4754, in notify_song
NameError: name 'song_notification' is not defined


This is log!

**Comment by Taiko2k** [comment]
Indeed I think this is already fixed. I've uploaded an updated Windows build here: https://github.com/Taiko2k/TauonMusicBox/releases/tag/v5.2.1

**Comment by emipta** [comment]
thanks a Lot Mr. Taiko2k , works !! :)
