### ISSUE TITLE
F5 view crashes in 1080x1920 fullscreen

### ISSUE THREAD

**Issue by C0rn3j** [Taiko2k/TauonMusicBox#242]
I've my 1920x1080 screen tilted 90°, so it is 1080x1920, this crashes TMB upon fullscreening it on the screen in the F5 view.
![image](https://user-images.githubusercontent.com/1641362/74602504-80dec680-50a9-11ea-94f5-0285f38651bb.png)

```
Maximize window
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 33037, in <module>
    showcase.render()
  File "/opt/tauon-music-box/tauon.py", line 28909, in render
    lyrics_ren.render(x,
  File "/opt/tauon-music-box/tauon.py", line 6832, in render
    ddt.text((x, y, 4, w), self.text, colour, 17, w, colours.playlist_panel_background)
  File "/opt/tauon-music-box/t_modules/t_draw.py", line 693, in text
    return self.__draw_text_cairo(location, text, colour, font, location[3], bg, max_y=max_h, wrap=True,
  File "/opt/tauon-music-box/t_modules/t_draw.py", line 465, in __draw_text_cairo
    surf = cairo.ImageSurface.create_for_data(data, cairo.FORMAT_RGB24, w, h)
ValueError: width must be positive
```
![TMB2](https://user-images.githubusercontent.com/1641362/74602486-470dc000-50a9-11ea-9929-d6aa07f22db4.gif)

**Comment by Taiko2k** [comment]
I see the issue. Indeed this issue only emerges with portrait shaped desktops. I've pushed a fix now.
