### ISSUE TITLE
[Crash] Windows 10 versión tauon-setup32-v5.2.2-beta1.exe (crash.log) 

### ISSUE THREAD

**Issue by emipta** [Taiko2k/TauonMusicBox#243]
Hi Taiko2k..

i have this log after crash.

2020-02-06 23:25:48,193 ERROR root Exception on player thread
Traceback (most recent call last):
  File "tauon.py", line 6388, in bass_player_thread
  File "t_modules\t_bass.py", line 1375, in player
  File "tauon.py", line 4121, in test_progress
  File "tauon.py", line 4593, in advance
  File "tauon.py", line 4754, in notify_song
NameError: name 'song_notification' is not defined
2020-02-16 18:33:45,817 ERROR root Exception on player thread
Traceback (most recent call last):
  File "tauon.py", line 6388, in bass_player_thread
  File "t_modules\t_bass.py", line 1375, in player
  File "tauon.py", line 4121, in test_progress
  File "tauon.py", line 4593, in advance
  File "tauon.py", line 4754, in notify_song
NameError: name 'song_notification' is not defined
2020-02-16 20:10:00,666 ERROR root Exception on player thread
Traceback (most recent call last):
  File "tauon.py", line 6388, in bass_player_thread
  File "t_modules\t_bass.py", line 1375, in player
  File "tauon.py", line 4121, in test_progress
  File "tauon.py", line 4593, in advance
  File "tauon.py", line 4754, in notify_song
NameError: name 'song_notification' is not defined
2020-02-16 20:42:11,983 ERROR root Exception on player thread
Traceback (most recent call last):
  File "tauon.py", line 6388, in bass_player_thread
  File "t_modules\t_bass.py", line 1375, in player
  File "tauon.py", line 4121, in test_progress
  File "tauon.py", line 4593, in advance
  File "tauon.py", line 4754, in notify_song
NameError: name 'song_notification' is not defined
2020-02-16 20:51:12,320 ERROR root Exception on player thread
Traceback (most recent call last):
  File "tauon.py", line 6388, in bass_player_thread
  File "t_modules\t_bass.py", line 1375, in player
  File "tauon.py", line 4121, in test_progress
  File "tauon.py", line 4593, in advance
  File "tauon.py", line 4754, in notify_song
NameError: name 'song_notification' is not defined
2020-02-17 23:24:26,348 ERROR root Exception on player thread
Traceback (most recent call last):
  File "tauon.py", line 6388, in bass_player_thread
  File "t_modules\t_bass.py", line 1375, in player
  File "tauon.py", line 4121, in test_progress
  File "tauon.py", line 4593, in advance
  File "tauon.py", line 4754, in notify_song
NameError: name 'song_notification' is not defined
2020-02-18 21:43:29,804 ERROR root Exception on player thread
Traceback (most recent call last):
  File "tauon.py", line 6388, in bass_player_thread
  File "t_modules\t_bass.py", line 1375, in player
  File "tauon.py", line 4121, in test_progress
  File "tauon.py", line 4593, in advance
  File "tauon.py", line 4754, in notify_song
NameError: name 'song_notification' is not defined

**Comment by Taiko2k** [comment]
I thought I fixed that... can you double check what version shows in the About page? It should say v5.2.2

**Comment by emipta** [comment]
Sorry Taiko, my fault..

i  have two versions installed, portable and last version.. 

5.2.2 is fine! 

All is good! .. thanks!
