### ISSUE TITLE
Fresh install crashes when resizing to minimum

### ISSUE THREAD

**Issue by phw** [Taiko2k/TauonMusicBox#29]
When I start Tauon with an empty config and try to resize the window to it's minimum it crashes with:

```
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 21952, in <module>
    top_panel.render()
  File "/app/bin/tauon.py", line 14862, in render
    p_text = trunc_line(pctl.title_text(), 12, window_size[0] - offset - 120 * gui.scale)
  File "/app/bin/tauon.py", line 2173, in title_text
    title = self.master_library[self.track_queue[self.queue_step]].title
IndexError: list index out of range
```

Once I have added some files this no longer happens.

**Comment by Taiko2k** [comment]
Nice find. Those kind of bugs are hard to catch since I rarely test with a blank slate. Ill have this fixed.
