### ISSUE TITLE
Segfault issue

### ISSUE THREAD

**Issue by Porkepix** [Taiko2k/TauonMusicBox#322]
At some point while the player was playing music, it crashed completely. I didn't had my headphones on my head at that time, can't know for sure what it was doing or playing.

Here's the complete `journald` log of the crash.

```
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Tauon Music Box v6.0.3
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Copyright 2015-2020 Taiko2k YOUR EMAIL
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Running from installed location
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: User files location: /home/clement/.local/share/TauonMusicBox
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Found XDG-Downloads: /home/clement/Downloads
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Found XDG-Music: /home/clement/Music
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Install directory: /opt/tauon-music-box
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Database loaded in 0.007 seconds.
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: No translation file available
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Applying scale based on xft setting
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: 1.0
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Using SDL version: 2.0.12
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Using GStreamer as fallback. Some functions disabled
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Config reload theme...
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load Bio Data
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Applying external theme: Turbo
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Theme number: 10
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load Bio Data
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load cached bio and image
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Save BMP to memory
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Enabling garbage collecting
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Create Texture
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Reset scrobble timer
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load Bio Data
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load cached bio and image
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load Bio Data
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Connection appears successful
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: save bio text
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Searching fanart.tv for image...
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Failed to find image from fanart.tv
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load Bio Data
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: save bio text
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load Bio Data
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: save bio text
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Searching fanart.tv for image...
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Found artist thumbnail from fanart.tv
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Save BMP to memory
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load Bio Data
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load cached bio and image
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load Bio Data
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: save bio text
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Searching fanart.tv for image...
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Found artist thumbnail from fanart.tv
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Save BMP to memory
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Create Texture
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Auto Save
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Load Bio Data
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: Traceback (most recent call last):
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]:   File "/opt/tauon-music-box/tauon.py", line 39210, in <module>
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]:     # if box[0] + 10 * gui.scale > start + (gui.plw - 25 * gui.scale):
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]:   File "/opt/tauon-music-box/tauon.py", line 33600, in draw
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]:     return
Jul 30 18:36:34 T470-clement tauonmb.desktop[81417]: TypeError: argument of type 'NoneType' is not iterable
Jul 30 18:36:34 T470-clement audit[81417]: ANOM_ABEND auid=1000 uid=1000 gid=985 ses=3 pid=81417 comm="tauonmb" exe=2F7573722F62696E2F707974686F6E332E38202864656C6574656429 sig=11 res=1
Jul 30 18:36:34 T470-clement kernel: tauonmb[81475]: segfault at 0 ip 00007f0f9bc53a4d sp 00007f0f63ffd9c0 error 4 in libpthread-2.31.so[7f0f9bc48000+10000]
Jul 30 18:36:34 T470-clement kernel: Code: ff f0 48 01 03 41 bd ff ff ff ff eb 94 e8 8b 4c ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 55 48 89 fd e8 c3 ed ff ff <48> 8b 45 00 85 c0 74 13 48 8d 50 ff f0 48 0f b1 55 00 75 07 31 c0
Jul 30 18:36:34 T470-clement kernel: audit: type=1701 audit(1596126994.758:710): auid=1000 uid=1000 gid=985 ses=3 pid=81417 comm="tauonmb" exe=2F7573722F62696E2F707974686F6E332E38202864656C6574656429 sig=11 res=1
Jul 30 18:36:34 T470-clement systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Jul 30 18:36:34 T470-clement kernel: audit: type=1334 audit(1596126994.875:711): prog-id=47 op=LOAD
Jul 30 18:36:34 T470-clement kernel: audit: type=1334 audit(1596126994.875:712): prog-id=48 op=LOAD
Jul 30 18:36:34 T470-clement kernel: audit: type=1130 audit(1596126994.875:713): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-178727-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 30 18:36:34 T470-clement audit: BPF prog-id=47 op=LOAD
Jul 30 18:36:34 T470-clement audit: BPF prog-id=48 op=LOAD
Jul 30 18:36:34 T470-clement audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-178727-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 30 18:36:34 T470-clement systemd[1]: Started Process Core Dump (PID 178727/UID 0).
Jul 30 18:36:38 T470-clement previews_creato[1230]: wnck_screen_get_active_window: assertion 'WNCK_IS_SCREEN (screen)' failed
Jul 30 18:36:38 T470-clement tauonmb.desktop[81416]: /opt/tauon-music-box/tauonmb.sh: line 2: 81417 Segmentation fault      (core dumped) python3 /opt/tauon-music-box/tauon.py "$@"
Jul 30 18:36:38 T470-clement systemd[810]: gnome-launched-tauonmb.desktop-81416.scope: Succeeded.
Jul 30 18:36:40 T470-clement systemd-coredump[178728]: Process 81417 (tauonmb) of user 1000 dumped core.

                                                       Stack trace of thread 81475:
                                                       #0  0x00007f0f9bc53a4d sem_wait@@GLIBC_2.2.5 (libpthread.so.0 + 0x12a4d)
                                                       #1  0x00007f0f9bd66dc2 n/a (/usr/lib/libpython3.8.so.1.0 (deleted) + 0x103dc2)
                                                       #2  0x0000000000000000 n/a (n/a + 0x0)
Jul 30 18:36:41 T470-clement systemd[1]: systemd-coredump@0-178727-0.service: Succeeded.
Jul 30 18:36:41 T470-clement kernel: audit: type=1131 audit(1596127000.998:714): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-178727-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 30 18:36:40 T470-clement audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@0-178727-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 30 18:36:41 T470-clement audit: BPF prog-id=48 op=UNLOAD
```

Coredumpctl info:
```
$ coredumpctl info 81417
           PID: 81417 (tauonmb)
           UID: 1000 (clement)
           GID: 985 (users)
        Signal: 11 (SEGV)
     Timestamp: Thu 2020-07-30 18:36:34 CEST (15min ago)
  Command Line: tauonmb
    Executable: /usr/bin/python3.8
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-launched-tauonmb.desktop-81416.scope
          Unit: user@1000.service
     User Unit: gnome-launched-tauonmb.desktop-81416.scope
         Slice: user-1000.slice
     Owner UID: 1000 (clement)
       Boot ID: b59260b9d9d34d6fb0ef6282814e7ef4
    Machine ID: c8ef63b932b54372a1d6c2571d18b83d
      Hostname: T470-clement
       Storage: /var/lib/systemd/coredump/core.tauonmb.1000.b59260b9d9d34d6fb0ef6282814e7ef4.81417.1596126994000000000000.lz4
       Message: Process 81417 (tauonmb) of user 1000 dumped core.

                Stack trace of thread 81475:
                #0  0x00007f0f9bc53a4d sem_wait@@GLIBC_2.2.5 (libpthread.so.0 + 0x12a4d)
                #1  0x00007f0f9bd66dc2 n/a (/usr/lib/libpython3.8.so.1.0 (deleted) + 0x103dc2)
                #2  0x0000000000000000 n/a (n/a + 0x0)
```

**Comment by Taiko2k** [comment]
I've also noticed some crashes like this lately. I haven't been able to reliably reproduce it.

My guess is its a bug in another recently updated Arch Linux package, likely the Python interpreter itself, I see that package got updated to 3.8.5 a few days ago.

**Comment by Hurqalia** [comment]
same problem, cant start tauon since version 6.0.0
> tauonmb[17407]: segfault at 10 ip 00007f82ed2096c0 sp 00007ffc8f5cb6b8 error 4 in libpthread-2.28.so[7f82ed205000+f000]
on debian buster with python3.7.3.2
output from a start in verbose mode

> # /opt/TauonMusicBox/t_modules/__pycache__/t_gdk_extra.cpython-37.pyc matches /opt/TauonMusicBox/t_modules/t_gdk_extra.py
> # code object from '/opt/TauonMusicBox/t_modules/__pycache__/t_gdk_extra.cpython-37.pyc'
> import 't_modules.t_gdk_extra' # <_frozen_importlib_external.SourceFileLoader object at 0x7fe6caa4a2e8>
> Segmentation fault
>

**Comment by Hurqalia** [comment]
same problem on debian buster with python3.7.3.2, cant start tauon since version 6.0.0.

`tauonmb[17407]: segfault at 10 ip 00007f82ed2096c0 sp 00007ffc8f5cb6b8 error 4 in libpthread-2.28.so[7f82ed205000+f000]`

output from a start in verbose mode
```
/opt/TauonMusicBox/t_modules/pycache/t_gdk_extra.cpython-37.pyc matches /opt/TauonMusicBox/t_modules/t_gdk_extra.py
code object from '/opt/TauonMusicBox/t_modules/pycache/t_gdk_extra.cpython-37.pyc'
import 't_modules.t_gdk_extra' # <_frozen_importlib_external.SourceFileLoader object at 0x7fe6caa4a2e8>
Segmentation fault
```

**Comment by Taiko2k** [comment]
@Hurqalia Hmm. I don't think thats the *exact* same issue since yours happens every time and the python version is somewhat different.

What happens when you delete the folder `/opt/TauonMusicBox/t_modules/pycache/`?

**Comment by Hurqalia** [comment]
@Taiko2k no, i'am using i3w

**Comment by Taiko2k** [comment]
@Hurqalia I found one possible source of the problem. I can't fix it because its a bug in another library, but I've added a way to bypass it. Try update/pull to latest version and run Tauon with the argument `--nogdk`

**Comment by Hurqalia** [comment]
it seems to work. The app is scanning the tags... 
just because of gdk cursors !!?? XD

**Comment by Taiko2k** [comment]
To summarise, I'm currently tracking 3 possible segfault issues:
 
- Crashes randomly on rare occasion. (Cause unknown. I haven't noticed this in a while (AUR install), is it fixed?)
- Crashes randomly on startup. (Possible GStreamer bug I think)
- Crashes constantly on startup. (GDK related bug with some environments, pass argument `--nogdk` to bypass)
