### ISSUE TITLE
[Bug] Tauon stops an Airsonic scan, and throws errors in the terminal

### ISSUE THREAD

**Issue by awsms** [Taiko2k/TauonMusicBox#415]
I never had any issue before while scanning an airsonic library, and now Tauon stops the scan at the exact same file everytime I try to relaunch the process (at 994 files scanned). I cleaned the network tracks cache before rescanning it.

```
Exception in thread Thread-647:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./tauon.py", line 7281, in get_music2
    get(id, name)
  File "./tauon.py", line 7228, in get
    get(item["id"], item["title"])
  File "./tauon.py", line 7228, in get
    get(item["id"], item["title"])
  File "./tauon.py", line 7228, in get
    get(item["id"], item["title"])
  File "./tauon.py", line 7215, in get
    d = self.r("getMusicDirectory", p={"id": folder_id})
  File "./tauon.py", line 7161, in r
    d = json.loads(response.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Taiko2k** [comment]
Must be some kind of error on accessing that folder. File error? Database error? I'm not sure. 

I've now committed a change to catch the error, so it will now skip over it and at least continue on with importing the rest.
