### ISSUE TITLE
Large Spotify playlist importation makes Tauon crash

### ISSUE THREAD

**Issue by kthys** [Taiko2k/TauonMusicBox#470]
Playlist importation works fine on small playlist but once I try to import a larger playlist (13 hours of music), Tauon crashes with this error stack :

```
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 43016, in <module>
    instance.render()
  File "/opt/tauon-music-box/tauon.py", line 12729, in render
    self.items[to_call][2](self.reference)
  File "/opt/tauon-music-box/t_modules/t_spot.py", line 561, in playlist
    nt = self.load_track(item.track, include_album_url=True)
  File "/opt/tauon-music-box/t_modules/t_spot.py", line 679, in load_track
    pr = self.current_imports.get(track.external_urls["spotify"])
KeyError: 'spotify'
```
I'm using Tauon from AUR.
The playlist contains songs with japanese characters which could be another reason for the crash.

**Comment by Taiko2k** [comment]
From the looks of it, it seems Tauon is assuming every track has an associated URL, and while most do, your big playlist happens to have one that doesn't. So it turns out its an incorrect assumption to make.

Shouldn't be too hard to fix though.

**Comment by Taiko2k** [comment]
I expect this to be fixed in the new release now. But let me know if you run into more issues with it as there may be more things that need fixing in relation to this.

**Comment by kthys** [comment]
I just updated Tauon and it looks like the bug is still there. The authorization works fine but when I try to import my playlist the error stack remains the same:
```
Init spotify support
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 43047, in <module>
    instance.render()
  File "/opt/tauon-music-box/tauon.py", line 12720, in render
    self.items[to_call][2](self.reference)
  File "/opt/tauon-music-box/t_modules/t_spot.py", line 563, in playlist
    nt = self.load_track(item.track, include_album_url=True)
  File "/opt/tauon-music-box/t_modules/t_spot.py", line 683, in load_track
    pr = self.current_imports.get(track.external_urls["spotify"])
KeyError: 'spotify'
```
The Tauon version is 6.5.3 and I updated it from AUR.

**Comment by kthys** [comment]
I found a way to fix it, don't hesitate to review my changes.
I could successfully import my playlists and the audio playback is working great !
