### ISSUE TITLE
Crash on start up with syntax error in tauon.py line 137

### ISSUE THREAD

**Issue by brunob** [Taiko2k/TauonMusicBox#568]
Hi, after upgrading from 0436a61a5f4b0d9fcaf34d70c7a633ae8a3c359f to ac2f0ac5f061aa79293d39d330c83a01fd7785b8 tauon crash on startup with error mentioned in title.

FTR, i'm on Ubutun 20.04.03 :)

**Comment by Taiko2k** [comment]
Odd, did it give any more information then just syntax error?

**Comment by brunob** [comment]
No more info but i just python tauon.py for testing, maybe i could have more info with an option on start ?

**Comment by Taiko2k** [comment]
Hmm, are you sure python is aliased to python 3 and not python 2?

**Comment by brunob** [comment]
Huhu, you're right, here is a more useful debug ;)

```
Tauon Music Box v6.7.2
Copyright 2015-2020 Taiko2k captain.gxj@gmail.com

Running in portable mode
Found XDG-Downloads: /home/bb/Téléchargements
Found XDG-Music: /home/bb/Musique
Install directory: 
Database loaded in 0.104 seconds.
Applying scale based on xft setting
Using UI scale: 1.0
WARNING: Missing library libopenmpt!
Traceback (most recent call last):
  File "tauon.py", line 225, in <module>
    exec(main)
  File "t_modules/t_main.py", line 21181, in <module>
    theme_files = os.listdir(install_directory + '/theme')
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/theme'
```

**Comment by Taiko2k** [comment]
That warning is unrelated. Both should be fixed now with latest commit. Tell me if its working now.

**Comment by brunob** [comment]
Strange, now i got an error mentionning `/Users/kai/tttb.txt` found here in source code https://github.com/Taiko2k/TauonMusicBox/blob/9137090532883589570b58a0355ecfc87febe637/t_modules/t_themeload.py#L41

```
Tauon Music Box v6.7.2
Copyright 2015-2020 Taiko2k captain.gxj@gmail.com

Running in portable mode
Found XDG-Downloads: /home/bb/Téléchargements
Found XDG-Music: /home/bb/Musique
Install directory: /home/bb/.local/share/applications/TauonMusicBox
Database loaded in 0.102 seconds.
Applying scale based on xft setting
Using UI scale: 1.0
WARNING: Missing library libopenmpt!
Start controller server
Init GStreamer...
Using SDL version: 2.0.10
Traceback (most recent call last):
  File "tauon.py", line 226, in <module>
    exec(main)
  File "/home/bb/.local/share/applications/TauonMusicBox/t_modules/t_main.py", line 39523, in <module>
    load_theme(c, theme[0])
  File "/home/bb/.local/share/applications/TauonMusicBox/t_modules/t_themeload.py", line 41, in load_theme
    a = open("/Users/kai/tttb.txt", "w")
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/Users/kai/tttb.txt'
```

**Comment by Taiko2k** [comment]
Oops, that's some leftover debug code I forgot to remove. Ive made another commit to remove it now.

**Comment by brunob** [comment]
(y) it works now, thx for the quick fix :)
