### ISSUE TITLE
Crash when writing tags of a track

### ISSUE THREAD

**Issue by nicolnt** [Taiko2k/TauonMusicBox#644]
Can't save fields on files when I want to edit tracks metadata, Tauon crashes when I click "WRITE TAGS" in the fields editor.

Logs:
```
Traceback (most recent call last):
  File "/app/bin/tauon.py", line 240, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 43462, in <module>
    trans_edit_box.render()
  File "/app/bin/t_modules/t_main.py", line 13619, in render
    print(muta["artist"])
  File "/app/lib/python3.9/site-packages/mutagen/_file.py", line 63, in __getitem__
    return self.tags[key]
  File "/app/lib/python3.9/site-packages/mutagen/easyid3.py", line 213, in __getitem__
    return func(self.__id3, key)
  File "/app/lib/python3.9/site-packages/mutagen/easyid3.py", line 120, in getter
    return list(id3[frameid])
  File "/app/lib/python3.9/site-packages/mutagen/_util.py", line 537, in __getitem__
    return self.__dict[key]
KeyError: 'TPE1'
```

Running using Flatpack on Debian 11
Tauon v6.8.2

**Comment by Taiko2k** [comment]
Looks like some left over debug code is causing it. Ive cleaned this up now and committed the fix.

**Comment by nicolnt** [comment]
OK thanks, I'll let you now when the next version is released 😉

**Comment by nicolnt** [comment]
I can confirm that this is now fixed! Thank you :D
