### ISSUE TITLE
'SDL_WINDOWEVENT_DISPLAY_CHANGED' is not defined

### ISSUE THREAD

**Issue by zkldi** [Taiko2k/TauonMusicBox#692]
Getting a fatal error when booting the latest version of tauon. Might be something to do with the fact I'm on manjaro?

Full errmsg is below.
```
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 246, in <module>
    exec(main)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 41328, in <module>
    elif event.window.event == SDL_WINDOWEVENT_RESIZED or event.window.event == SDL_WINDOWEVENT_DISPLAY_CHANGED:
NameError: name 'SDL_WINDOWEVENT_DISPLAY_CHANGED' is not defined
```

**Comment by zkldi** [comment]
Thanks. Interestingly from the AUR doesn't seem to do anything for me, I had to run `python -m pip install pysdl2 -U`. I think my python environments might just be messed up.
