### ISSUE TITLE
Error module 'PIL.Image' has no attribute 'Resampling'

### ISSUE THREAD

**Issue by brunob** [Taiko2k/TauonMusicBox#767]
Hi @Taiko2k 

Since today i've seen albums missing album arts, so i've resetting cover arts cache and now i haven't any cover displayed. Starting tauon from the CLI give me this error.

Here are my requirements state :

```
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (7.0.0)
Requirement already satisfied: pylast>=3.1.0 in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (3.2.1)
Requirement already satisfied: PySDL2 in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.9.11)
Requirement already satisfied: Send2Trash in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (2.22.0)
Requirement already satisfied: beautifulsoup4 in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (4.9.0)
Requirement already satisfied: PlexAPI in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (3.4.0)
Requirement already satisfied: musicbrainzngs in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (0.7.1)
Requirement already satisfied: isounidecode in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (0.3)
Requirement already satisfied: setproctitle in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (1.1.10)
Requirement already satisfied: pulsectl in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (21.10.4)
Requirement already satisfied: mutagen in /usr/lib/python3/dist-packages (from -r requirements.txt (line 12)) (1.44.0)
Requirement already satisfied: natsort in /home/bb/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (7.1.1)
Requirement already satisfied: soupsieve>1.2 in /home/bb/.local/lib/python3.8/site-packages (from beautifulsoup4->-r requirements.txt (line 6)) (2.0)
Requirement already satisfied: websocket-client in /home/bb/.local/lib/python3.8/site-packages (from PlexAPI->-r requirements.txt (line 7)) (0.57.0)
Requirement already satisfied: tqdm in /home/bb/.local/lib/python3.8/site-packages (from PlexAPI->-r requirements.txt (line 7)) (4.45.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from websocket-client->PlexAPI->-r requirements.txt (line 7)) (1.14.0)
```

Reading https://stackoverflow.com/questions/71738218/module-pil-has-not-attribute-resampling it seems to be a problem with recent Pillow versions. 

I also have this error in logs, but it doesn't seems related : 

```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bb/.local/share/applications/TauonMusicBox/t_modules/t_phazor.py", line 467, in player4
    aud.phazor_shutdown()
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/bb/.local/share/applications/TauonMusicBox/lib/libphazor.so: undefined symbol: phazor_shutdown
```

**Comment by brunob** [comment]
A fix could be replace of `Image.Resampling.LANCZOS` by `Image.LANCZOS`cf https://stackoverflow.com/a/72346841

**Comment by Taiko2k** [comment]
The pillow error is caused by using an old version of pillow, updating to latest should fix it. 

The 2nd error should be solved by running `compile-phazor.sh`, which I recommend doing after any pull.

**Comment by brunob** [comment]
`pip3 install --upgrade --user -r requirements.txt` did the trick, sorry for the noise, maybe we should add this to https://github.com/Taiko2k/TauonMusicBox/wiki/Raspberry-Pi#manual-setup ?

I've already tried to run phazor compile script but it print an error :

```
compile-phazor.sh: 5: [[: not found
compile-phazor.sh: 12: [[: not found
compile-phazor.sh: 19: [[: not found
-e == == == == == == 
 Unsupported OS. 
== == == == == ==
```

**Comment by RSKYS** [comment]
> compile-phazor.sh: 5: [[: not found
compile-phazor.sh: 12: [[: not found
compile-phazor.sh: 19: [[: not found

@brunob I don't see why it should give error;
Syntax should be fine since `#!/bin/bash` is present at the beginning of script.
Could you specify more details on how you ran it and got into issue?

**Comment by brunob** [comment]
@RSKYS & @Taiko2k sorry to borrow with that, but today i got this error :

```
Start PHAzOR backend...
Using SDL version: 2.0.10
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bb/.local/share/applications/TauonMusicBox/t_modules/t_phazor.py", line 431, in player4
    set_config()
  File "/home/bb/.local/share/applications/TauonMusicBox/t_modules/t_phazor.py", line 425, in set_config
    aud.config_set_resample(prefs.avoid_resampling ^ True)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/bb/.local/share/applications/TauonMusicBox/lib/libphazor.so: undefined symbol: config_set_resample
```

So i tried to compile phazor and i get this error :

```
./compile-phazor.sh 
gcc: error: src/phazor/kissfft/kiss_fftr.c: Aucun fichier ou dossier de ce type
gcc: error: src/phazor/kissfft/kiss_fft.c: Aucun fichier ou dossier de ce type
```

Git repo is up and all python requirements too, can you tell me how to fix phazor compilation please ?

**Comment by Taiko2k** [comment]
@brunob `git submodule update --init --recursive`

**Comment by brunob** [comment]
FTR, i've run in the same issue this morning, here is what i've done to fix the problem :

1) the classic part with

```
git pull
git submodule update --init --recursive
pip3 install  -upgrade --user -r requirements.txt
```

Then i get an error with PyGObject installation that i've fixed with `apt install libcairo2-dev`, then another error fixed with `apt install libgirepository1.0-dev` ref https://github.com/pygobject/pycairo/issues/89

Then another error fixed with `apt install libdbus-1-dev`.

After that `pip3 install --upgrade --user -r requirements.txt` run without error and i finally got all covers displayed well.

Maybe the https://github.com/Taiko2k/Tauon/wiki/Building#debianubuntu doc need an update ?
