### ISSUE TITLE
UI goes unresponsive when playback starts

### ISSUE THREAD

**Issue by jansol** [Taiko2k/TauonMusicBox#801]
Seems MPRIS still has some issues as of 99f6f7c983551885e3e6e909425905310e01402d:
```python
Exception in thread Thread-9 (notify_update_fire):
Traceback (most recent call last):
  File "/nix/store/ddhcwc8k9ma093n5vlpa9l617p4q2cax-python3-3.10.5/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/nix/store/ddhcwc8k9ma093n5vlpa9l617p4q2cax-python3-3.10.5/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/nix/store/dahcdw45z9c8z8dw6bm0y0v2qz605v5w-tauon-7.3.2/share/tauon/t_modules/t_main.py", line 5089, in notify_update_fire
    self.mpris.update()
  File "/nix/store/dahcdw45z9c8z8dw6bm0y0v2qz605v5w-tauon-7.3.2/share/tauon/t_modules/t_dbus.py", line 394, in update
    id = f"/com/tauon/{track.index}/{abs(pctl.playlist_playing_position)}"
TypeError: bad operand type for abs(): 'NoneType'
```

**Comment by Taiko2k** [comment]
Its more there's a bug elsewhere in the program and this is a side effect.

Do you remember what you were doing when it crashed? Were you using the queue feature? Did you have shuffle on?

**Comment by jansol** [comment]
No queue, shuffle was _on_ IIRC. I just launched Tauon, resized the window and hit the play button.

**Comment by jansol** [comment]
Oh, actually there may have been some songs queued earlier when I closed tauon. However after it started hanging restarting has not changed anything and it at least does not show that there is anything queued when it starts.

**Comment by Taiko2k** [comment]
Does this happen every time or was it a one off?

**Comment by jansol** [comment]
It's been happening every time after it started.

**Comment by Taiko2k** [comment]
Not sure what caused it but it should be fixed when you next update now

**Comment by jansol** [comment]
Latest git ([677f4a8](https://github.com/Taiko2k/TauonMusicBox/commit/677f4a8dcd46faab2f5c3a5b214355439161402b)) does indeed seem to be working again.
