### ISSUE TITLE
Cannot play anything after updating my system [AUR]

### ISSUE THREAD

**Issue by talhakerpicci** [Taiko2k/TauonMusicBox#838]
Hey there. Yesterday i updated my system and this morning, i cannot play any media. Here are the logs:

```
Tauon Music Box v7.4.0
Copyright 2015-2022 Taiko2k captain.gxj@gmail.com

Window size: [300, 300]
Running from installed location
User files location: /home/anon/.local/share/TauonMusicBox
Found XDG-Downloads: /hdd/Downloads
Found XDG-Music: /hdd/Music
Install directory: /opt/tauon-music-box
Database loaded in 0.085 seconds.
Pychromecast not found
Start controller server
Start PHAzOR backend...
Exception in thread Thread-6 (player4):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/tauon-music-box/t_modules/t_phazor.py", line 58, in player4
    aud = ctypes.cdll.LoadLibrary(pctl.install_directory + "/lib/libphazor.so")
Using SDL version: 2.24.0
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libFLAC.so.8: cannot open shared object file: No such file or directory
Applying theme: Neon Love
Start PHAzOR backend...
Exception in thread Thread-12 (player4):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/tauon-music-box/t_modules/t_phazor.py", line 58, in player4
    aud = ctypes.cdll.LoadLibrary(pctl.install_directory + "/lib/libphazor.so")
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libFLAC.so.8: cannot open shared object file: No such file or directory
```

Im on arch linux running version 7.4.0 of Tauon Music Box

**Comment by Taiko2k** [comment]
Just need to rebuild the Tauon AUR package. This affects everyone so I've bumped the pkgrel now.

**Comment by talhakerpicci** [comment]
Oh just rebuilt it and everything is fine now. Thank you so much for the quick reply!

**Comment by Qwerty-Space** [comment]
I'm unable to build tauon from the AUR currently, so I can't rebuild
