### ISSUE TITLE
tauon now works :( 

### ISSUE THREAD

**Issue by emipta** [Taiko2k/TauonMusicBox#86]
Have a problem on my laptop and desktop, after install tauon on my debian and not works .. 

¿need python or other think? 

copy&paste : 

emi@Rygel:~$ flatpak run com.github.taiko2k.tauonmb
Tauon Music Box
v4.0.0
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Detected running as Flatpak
Running from installed location
User files location: /home/emi/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Install directory: /app/bin
Could not set process title.
Locale detected: ('es_ES', 'UTF-8')
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/sdl2/dll.py", line 113, in <module>
    dll = DLL("SDL2", ["SDL2", "SDL2-2.0"], os.getenv("PYSDL2_DLL_PATH"))
  File "/app/lib/python3.7/site-packages/sdl2/dll.py", line 54, in __init__
    (libinfo, dllmsg))
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/tauon.py", line 344, in <module>
    from sdl2 import *
  File "/app/lib/python3.7/site-packages/sdl2/__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "/app/lib/python3.7/site-packages/sdl2/dll.py", line 115, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

**Comment by Taiko2k** [comment]
Something strange going on...

I see it says v4.0.0, but the latest is v4.1.0 (just released)

Try run `flatpak update` and see what happens then

**Comment by emipta** [comment]
I have now 4.1 and flatpak 0.8.9 and same problem..


emi@Rygel:~$ flatpak run com.github.taiko2k.tauonmb
Tauon Music Box
v4.1.0
Copyright 2015-2019 Taiko2k captain.gxj@gmail.com

Detected running as Flatpak
Running from installed location
User files location: /home/emi/.var/app/com.github.taiko2k.tauonmb/data/TauonMusicBox
Install directory: /app/bin
Could not set process title.
Locale detected: ('es_ES', 'UTF-8')
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/sdl2/dll.py", line 113, in <module>
    dll = DLL("SDL2", ["SDL2", "SDL2-2.0"], os.getenv("PYSDL2_DLL_PATH"))
  File "/app/lib/python3.7/site-packages/sdl2/dll.py", line 54, in __init__
    (libinfo, dllmsg))
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bin/tauon.py", line 342, in <module>
    from sdl2 import *
  File "/app/lib/python3.7/site-packages/sdl2/__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "/app/lib/python3.7/site-packages/sdl2/dll.py", line 115, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)
emi@Rygel:~$ 


thanks Taiko2k !

**Comment by emipta** [comment]
Solved!!! 

root@Rygel:/home/emi# flatpak --version
Flatpak 1.2.4
root@Rygel:/home/emi# 

now works ..


thanks a lot Taiko2k
