### ISSUE TITLE
Radio stops playing

### ISSUE THREAD

**Issue by Solarunit** [Taiko2k/TauonMusicBox#943]
Radio stops playing very often, here is exception:

```
Send heatbeat
{"op":10}
Send heatbeat
{"op":10}
Websocket closed
Abort stream connection
Exit feeder
Exception in thread Thread-32 (send_heartbeat):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_main.py", line 34962, in send_heartbeat
    ws.send("{\"op\":9}")
  File "/app/lib/python3.10/site-packages/websocket/_app.py", line 204, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
```

PS: listen.moe radio

**Comment by Taiko2k** [comment]
Are you sure you're not hitting the pause button? There was a recent change in which pausing now has effect of stopping the stream.

**Comment by Solarunit** [comment]
>Are you sure you're not hitting the pause button?

It's possible, bcs I have a shortcut for it and I am using it very often..
Will test more today/tomorrow.

**Comment by Solarunit** [comment]
Radio works fine so far, but I noticed a Traceback when switching to play song in the local playlist:

```
Send heatbeat
{"op":10}
Send heatbeat
{"op":10}
Websocket closed
Abort stream connection
Exit feeder
ph: Jump
pa: Reset position counter
Exception in thread Thread-123 (send_heartbeat):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_main.py", line 34962, in send_heartbeat
    ws.send("{\"op\":9}")
  File "/app/lib/python3.10/site-packages/websocket/_app.py", line 204, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
pa: Reset position counter
```

**Comment by Taiko2k** [comment]
That error is benign. I should probably suppress it.

**Comment by Solarunit** [comment]
It happened just now when I was listening to the radio: "Stream download thread crashed! Exit feeder"

```
Got new art
{"op":10}
NEXT RADIO TRACK
Send heatbeat
{"op":10}
Send heatbeat
{"op":10}
Send heatbeat
{"op":10}
Stream download thread crashed!
Exit feeder
Send heatbeat
{"op":10}
Send heatbeat
{"op":10}
Send heatbeat
{"op":10}

```

After that no output in the terminal. When I am trying to play a song from the local playlist, nothing happens, also no output. Had to restart tauon.

**Comment by Solarunit** [comment]
done!

![](https://i.imgur.com/n7g7Tyb.png)

**Comment by Solarunit** [comment]
Another one today:

```
Send heatbeat
{"op":10}
Send heatbeat
{"op":10}
Stream download thread crashed!
Exception in thread Thread-18 (run_download):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_stream.py", line 438, in run_download
    chunk = r.read(256)
  File "/usr/lib/python3.10/http/client.py", line 459, in read
    return self._read_chunked(amt)
  File "/usr/lib/python3.10/http/client.py", line 582, in _read_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.10/http/client.py", line 565, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.10/http/client.py", line 525, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
Send heatbeat
```

**Comment by Taiko2k** [comment]
The issue seems to be that its timing out. Could be that your connection is unstable. Ive make a commit that increases the timeout, I'm not getting the feeling that will help but you could see. The only next step I can think of is adding a restart mechanism, though that will produce an audible gap when it reconnects.

**Comment by Solarunit** [comment]
> Could be that your connection is unstable.

I haven't noticed any problems with other sites..
Also when radio stops playing, tauon can't play same radio again or local playlist.

**Comment by Solarunit** [comment]
Again today:

```
Send heatbeat
{"op":10}
Stream download thread crashed!
Exception in thread Thread-18 (run_download):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_stream.py", line 438, in run_download
    chunk = r.read(256)
  File "/usr/lib/python3.10/http/client.py", line 459, in read
    return self._read_chunked(amt)
  File "/usr/lib/python3.10/http/client.py", line 582, in _read_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.10/http/client.py", line 565, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.10/http/client.py", line 525, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out
Send heatbeat
{"op":10}
```

After that I was trying to play a local song in the playlist:

```
No image
NEXT RADIO TRACK
Websocket closed
Exit feeder
Exception in thread Thread-61 (send_heartbeat):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_main.py", line 34962, in send_heartbeat
    ws.send("{\"op\":9}")
  File "/app/lib/python3.10/site-packages/websocket/_app.py", line 204, in send
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
Websocket closed
Websocket closed
Websocket closed
Websocket closed
Websocket closed
Websocket closed
Websocket closed
Websocket closed
Websocket closed
Websocket closed
Websocket closed
Shutting down. Reason: User clicked X button
Writing database to disk... done
Stopping stream...
Websocket closed
```

With no response I closed tauon.

**Comment by Taiko2k** [comment]
Did you do git pull since before?

**Comment by Solarunit** [comment]
No, it's flatpak version..

**Comment by Solarunit** [comment]
v.7.6.0 Flatpak
got one today:

```
Send heatbeat
{"op":10}
Stream download thread crashed!
Exception in thread Thread-20 (feed):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/t_modules/t_stream.py", line 177, in feed
    decoder.stdin.write(chunk)
BrokenPipeError: [Errno 32] Broken pipe
Send heatbeat
{"op":10}
Send heatbeat
{"op":10}
Send heatbeat
{"op":10}
Shutting down. Reason: User clicked X button
Writing database to disk... done

```

**Comment by Solarunit** [comment]
Interesting, I am listening to Gensokyo Radio for some time, and there wasn't interruptions so far, maybe the problem with isten.moe stream itself? :thinking:

**Comment by C0rn3j** [comment]
@Solarunit is this still the case on current master? If so, please post the log.

**Comment by Solarunit** [comment]
@C0rn3j I am on latest flatpak. Periodically radio stops playing for several seconds or indefinitely, when it happens it's not possible to switch to another radio or close tauon. I have to kill the process.

**Comment by C0rn3j** [comment]
Latest release (7.8.3) is missing major overhauls including but not limited to, better logging:  
https://github.com/Taiko2k/Tauon/blob/master/CHANGELOG.md#v790

If you could reproduce it on git master and post the current logs to confirm it's still there and perhaps get some better logs to track down, that'd be neat!

Or wait for 7.9.0 to be released and do it then.

**Comment by Solarunit** [comment]
>Or wait for 7.9.0 to be released and do it then.

that's the plan

>It sounds to me like the radio processing is
>blocking the UI thread

yea

**Comment by C0rn3j** [comment]
Can you retest on pre-release 7.9.0 flatpak?

See this comment https://github.com/Taiko2k/Tauon/issues/1084#issuecomment-2571286287 for more details.
