### ISSUE TITLE
.IT files played from Jellyfin play for a short while then stop quite early

### ISSUE THREAD

**Issue by Someone65** [Taiko2k/TauonMusicBox#954]
Running Jellyfin 10.8.7 and TMB 7.5.0, .IT files playing from Jellyfin do play properly, but only momentarily after which they stop playing and skip over to the next song. Not sure if this is just a Jellyfin issue that has to be solved on its end and not TMB...

**Comment by Taiko2k** [comment]
In Tauon does it show a time duration for the track?

**Comment by Someone65** [comment]
It shows a time duration of 0:00, which Jellyfin's web client does, too as it can't even play .IT files.

**Comment by Taiko2k** [comment]
Tauon will skip after 2 secs if no duration is provided. I need to change this so it re-checks the duration from the file itself on starting playback.

**Comment by C0rn3j** [comment]
Is this still a problem today on the latest [development build](https://github.com/Taiko2k/Tauon/wiki/Development-builds)? 

Looks to perhaps work fine for me nowadays with 0:00 files on local files at least.

**Comment by Someone65** [comment]
> Is this still a problem today on the latest [development build](https://github.com/Taiko2k/Tauon/wiki/Development-builds)?
> 
> Looks to perhaps work fine for me nowadays with 0:00 files on local files at least.

Same thing is still happening including the skipping:
![image](https://github.com/user-attachments/assets/2af4e980-48ba-40a0-8ea9-bb20d8fecbc3)

**Comment by C0rn3j** [comment]
Can you post the log (press ` or toggle console in Misc right click menu) and drag n drop a couple of the problematic files in here?

https://cloud.rys.rs/s/53kyy2ZeERSecAY

**Comment by Someone65** [comment]
Huh... I'm consistently crashing when I try to open the console with this error:
![image](https://github.com/user-attachments/assets/7cfa661b-ec76-475a-b6e8-f71d2b384b9c)

**Comment by C0rn3j** [comment]
Can you copypaste the full error here?

**Comment by Someone65** [comment]
I won't let me as when this happens the whole thing just locks up and I can't copy anything from there.

**Comment by C0rn3j** [comment]
Try the build from this commit (should be up in 20 minutes) - 
 https://github.com/C0rn3j/Tauon/commit/b2cb7717f27a7554ac7d4ba83213f6a6ac592b01

It should open up a console with the logs.

**Comment by C0rn3j** [comment]
So this is in part #1390 and in part its own problem in that the IT files do not have duration.

Now that https://github.com/Taiko2k/Tauon/pull/1402 is merged Tauon should have working logging even on Windows as long as you create an extensionless `debug` file (can be empty) within the user data folder, if you could post that log, that'd be neat.

**Comment by C0rn3j** [comment]
@Someone65 could you drop me a broken .IT file here that I can test with? https://cloud.rys.rs/s/g82Yb52ifx53wHy

**Comment by Someone65** [comment]
Oops, sorry I haven't been paying much attention here lol. I'll test for broken files later today and send some over.

**Comment by Someone65** [comment]
Okay, tried the latest Tauon and can confirm the ending early and having no duration is still an issue. I uploaded the zipped up files to your cloud storage folder (I think I uploaded two copies by accident whoopsie).

**Comment by C0rn3j** [comment]
Can you please 

* Go to `C:\Users\Yeet\AppData\Local\TauonMusicBox` (replace Yeet with your user),
*  *BACK IT UP*, we may need it for reproducing the issue
* Delete ffmpeg/ffprobe off it
* Launch Tauon
* Try playing the song (which should trigger downloading current ffmpeg version)
* Delete the imported playlist
* Reimport the playlist

And verify if all works now?

I cannot reproduce your issue and I suspect that your downloaded ffmpeg version is simply too old and buggy.

If this does not help 

* Go to Menu -> Settings and enable Debug mode in the last function page - which saves a log to the same directory as above.
* Restart Tauon
* Delete and reimport the playlist
* Try playing a broken song
* Post the Tauon.log (or however the file is named)

**Comment by Someone65** [comment]
I can confirm it doesn't work despite following all the steps exactly. Attached is the log.

[tauon.log](https://github.com/user-attachments/files/25866204/tauon.log)

**Comment by C0rn3j** [comment]
Which Jellyfin version do you currently run? It works both on Windows and Linux for me on 10.11.6.

If you also get the issue on 10.11.x, could you make me an account on your server and [send me the details](https://rys.rs/contact)? 


Here's the interesting bits from the log that we should probably do something about:

```python
[ ERROR ] Jelly exception on get size
Traceback (most recent call last):
  File "tauon/t_modules/t_jellyfin.py", line 474, in ingest_library
KeyError: 'Size'
```
```python
[ ERROR ] Jellyfin album art api error: 404 "skyline_-_ikes_house_destroyed does not have an image of type Primary"
# https://github.com/Taiko2k/Tauon/pull/2064
[ ERROR ] Failed to work with thumbnail
Traceback (most recent call last):
  File "PIL/Image.py", line 3518, in open
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tauon/t_modules/t_main.py", line 5611, in worker_render
  File "PIL/Image.py", line 3520, in open
AttributeError: 'NoneType' object has no attribute 'read'
```
```python
# https://github.com/Taiko2k/Tauon/issues/2063
Traceback (most recent call last):
  File "tauon/t_modules/t_main.py", line 5617, in worker_render
  File "tauon/t_modules/t_main.py", line 21486, in get_error_img
  File "PIL/Image.py", line 3512, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Tauon Music Box\\_internal\\assets\\load-error.png'
```

```python
[ ERROR ] Failed loading file through Mutagen
Traceback (most recent call last):
  File "tauon/t_modules/t_main.py", line 17067, in tag_scan
AttributeError: 'NoneType' object has no attribute 'info'
```

**Comment by Someone65** [comment]
Currently running on 10.11.0 rc5 according to the dashboard. Contacted you through Telegram with details.

**Comment by C0rn3j** [comment]
Regarding the Size KeyError, it was truly missing from the response:
```python
{'Protocol': 'File', 'Id': '156c3b47a23b5f02b7a82c2f1944068b', 'Path': 'D:\\Music\\Skyline\\goal.it', 'Type': 'Default', 'Container': 'it', 'Name': 'goal', 'IsRemote': False, 'ETag': '7c45df0d3869c46073bc58906e733a69', 'ReadAtNativeFramerate': False, 'IgnoreDts': False, 'IgnoreIndex': False, 'GenPtsInput': False, 'SupportsTranscoding': True, 'SupportsDirectStream': True, 'SupportsDirectPlay': True, 'IsInfiniteStream': False, 'UseMostCompatibleTranscodingProfile': False, 'RequiresOpening': False, 'RequiresClosing': False, 'RequiresLooping': False, 'SupportsProbing': True, 'MediaStreams': [], 'MediaAttachments': [], 'Formats': [], 'RequiredHttpHeaders': {}, 'TranscodingSubProtocol': 'http', 'HasSegments': False}
```

Turns out that this was a Jellyfin bug and removing the library and readding it to rescan it again fixed the issue.
