### ISSUE TITLE
tauon 7.6.0 crashes when selecting an artist with only 1 item in the artist tab

### ISSUE THREAD

**Issue by legacychimera247** [Taiko2k/TauonMusicBox#958]
well i guess the title says enough :)

this is the terminal output

`Traceback (most recent call last):
  File "/app/bin/tauon.py", line 350, in <module>
    exec(main)
  File "/app/bin/t_modules/t_main.py", line 45969, in <module>
    artist_list_box.render(*panel_rect)
  File "/app/bin/t_modules/t_main.py", line 37650, in render
    self.draw_card(artist, x, round(yy), w)
  File "/app/bin/t_modules/t_main.py", line 37470, in draw_card
    track = pctl.g(default_playlist[c])
IndexError: list index out of range`

no problems in the general music tab

**Comment by legacychimera247** [comment]
hello, this is solved, thank you...
