### ISSUE TITLE
Spotify authorization not working

### ISSUE THREAD

**Issue by kreatoo** [Taiko2k/TauonMusicBox#961]
Distro: KDE Neon
Installed through Flatpak, version 7.6.0.

When i authorize Spotify, it doesnt authorize and gives this in the console.

```
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 34244)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 432, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 420, in handle_one_request
    method()
  File "/app/bin/t_modules/t_webserve.py", line 742, in do_GET
    self.send_response(200)
  File "/usr/lib/python3.10/http/server.py", line 497, in send_response
    self.log_request(code)
  File "/usr/lib/python3.10/http/server.py", line 549, in log_request
    self.log_message('"%s" %s %s',
  File "/app/bin/t_modules/t_webserve.py", line 735, in log_message
    gui.console.print(format % args)
NameError: name 'gui' is not defined
----------------------------------------
```

I followed the guide properly, including giving the Client ID and putting the Redirect URL.

**Comment by Taiko2k** [comment]
Ah dang it, its a recent bug. Ive pushed an emergency release now with a fix. Flatpak should update soon.
