### ISSUE TITLE
Crashes when trying to connect to last.fm

### ISSUE THREAD

**Issue by huge-pancake** [Taiko2k/TauonMusicBox#987]
Info:

- Installing method: AUR.
- Version: See the following logs.

Steps:

1. Type `tauon` to open in terminal.
2. Click buttons: `MENU` > `Settings` > `Accounts`
3. Click buttons: `Last.fm` > `Login`.
4. ... allow access ...
5. Click button: `Done`.

Then it crashes.

Log:

```
Tauon Music Box v7.6.4
Copyright 2015-2023 Taiko2k captain.gxj@gmail.com

Window size: [1892, 1012]
Running from installed location
User files location: /home/pancak/.local/share/TauonMusicBox
Found XDG-Downloads: /home/pancak/Downloads
Found XDG-Music: /home/pancak/Music
Install directory: /opt/tauon-music-box
Database loaded in 0.002 seconds.
Pychromecast not found
Start controller server
Start PHAzOR backend...
Using SDL version: 2.26.5
Applying default theme: Mindaro
Connection appears successful
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/lib/python3.11/site-packages/httpcore/backends/sync.py", line 28, in read
    return self._sock.recv(max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1263, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1136, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 90, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 116, in handle_request
    raise exc
  File "/usr/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 95, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 159, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 195, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpcore/backends/sync.py", line 26, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pylast/__init__.py", line 923, in _download_response
    response = client.post(f"{host_subdir}{username}", data=self.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 1132, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 350, in <module>
    exec(main)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 46329, in <module>
    pref_box.render()
  File "/opt/tauon-music-box/t_modules/t_main.py", line 30088, in render
    self.tabs[self.tab_active][1](x + side_width, y + header_width, content_width, content_height)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 28751, in last_fm_box
    self.button(x, y, _("Login"), lastfm.auth1)
  File "/opt/tauon-music-box/t_modules/t_main.py", line 28011, in button
    plug()
  File "/opt/tauon-music-box/t_modules/t_main.py", line 6941, in auth1
    self.url = self.sg.get_web_auth_url()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pylast/__init__.py", line 1020, in get_web_auth_url
    token = self._get_web_auth_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pylast/__init__.py", line 1009, in _get_web_auth_token
    doc = request.execute()
          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pylast/__init__.py", line 947, in execute
    response = self._download_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pylast/__init__.py", line 925, in _download_response
    raise NetworkError(self.network, e) from e
pylast.NetworkError: NetworkError: The read operation timed out
```

**Comment by huge-pancake** [comment]
Sorry, I looked at the logs again and saw this

```
pylast.NetworkError: NetworkError: The read operation timed out
```

so it seems that it's my network problem.

I'll close this issue after I success.

**Comment by Taiko2k** [comment]
Yeah what Tauon is trying to do here is open a port and run a local http service. Perhaps your network configuration is preventing that somehow, not too sure.

**Comment by huge-pancake** [comment]
Done :P
